module jgine {
	requires org.eclipse.jdt.annotation;
	requires org.lwjgl;
	requires transitive org.lwjgl.glfw;
	requires transitive org.lwjgl.stb;
	requires transitive org.lwjgl.assimp;
	requires transitive org.lwjgl.opengl;
	requires transitive org.lwjgl.openal;
	requires transitive java.sql;
	requires transitive java.desktop;
	requires transitive java.scripting;
	requires transitive com.google.common;
	requires transitive it.unimi.dsi.fastutil;
	requires transitive com.fasterxml.jackson.databind;
	requires transitive org.yaml.snakeyaml;
	requires transitive org.graalvm.polyglot;
	requires transitive org.graalvm.js.scriptengine;
	requires transitive org.reflections;

	exports jgine.core;
	exports jgine.core.input;
	exports jgine.core.input.device;
	exports jgine.core.sound;
	exports jgine.core.sound.effect;
	exports jgine.core.window;
	exports jgine.net;
	exports jgine.net.game;
	exports jgine.net.game.packet;
	exports jgine.net.game.packet.listener;
	exports jgine.net.game.packet.packets;
	exports jgine.net.http;
	exports jgine.net.http.annotation;
	exports jgine.net.http.controller;
	exports jgine.net.ssl;
	exports jgine.render;
	exports jgine.render.light;
	exports jgine.render.material;
	exports jgine.render.mesh;
	exports jgine.render.shader;
	exports jgine.render.text;
	exports jgine.system;
	exports jgine.system.ai;
	exports jgine.system.ai.goals;
	exports jgine.system.ai.navigation;
	exports jgine.system.camera;
	exports jgine.system.collision;
	exports jgine.system.collision.collider;
	exports jgine.system.graphic;
	exports jgine.system.input;
	exports jgine.system.input.handler;
	exports jgine.system.light;
	exports jgine.system.particle;
	exports jgine.system.physic;
	exports jgine.system.script;
	exports jgine.system.tileMap;
	exports jgine.system.transform;
	exports jgine.system.ui;
	exports jgine.system.ui.objects;
	exports jgine.utils;
	exports jgine.utils.collection;
	exports jgine.utils.collection.bitSet;
	exports jgine.utils.collection.function;
	exports jgine.utils.collection.heap;
	exports jgine.utils.collection.list;
	exports jgine.utils.collection.list.offheap;
	exports jgine.utils.collection.map;
	exports jgine.utils.collection.pool;
	exports jgine.utils.collection.queue;
	exports jgine.utils.collection.tree;
	exports jgine.utils.loader;
	exports jgine.utils.math;
	exports jgine.utils.math.rotation;
	exports jgine.utils.math.vector;
	exports jgine.utils.memory;
	exports jgine.utils.registry;
	exports jgine.utils.scheduler;
	exports jgine.utils.spacePartitioning;
}